export const teamData = {
  Stratcom: [
    {
      name: "Atul Soneeth",
      position: "CHIEF ID8tor",
      email: "attul@id8nxt.com",
      mobile: "+1234567890",
      hoverImg: "/images/about/about-team/atul-s.png",
      img: "/images/about/about-team/atul-new.png",
    },
    {
      name: "Asif Akbar",
      position: "Creative Director",
      email: "asif.akbar@id8nxt.com",
      mobile: "+1234567891",
      hoverImg: "/images/about/about-team/asif-a.png",
      img: "/images/about/about-team/asid-a-1.png",
    },
    {
      name: "Madhav Barve",
      position: "Key Account Manager",
      email: "madhav.barve@id8nxt.com",
      mobile: "+1234567892",
      hoverImg: "/images/about/about-team/madhav.png",
      img: "/images/about/about-team/madhav-new.png",
    },
    {
      name: "Amina Sayed",
      position: "Lead Key Account Manager",
      email: "amina.sayed@id8nxt.com",
      mobile: "+1234567893",
      hoverImg: "/images/about/about-team/amina-s.png",
      img: "/images/about/about-team/amina-1.png",
    },
    {
      name: "Nina Patel",
      position: "Content Strategist",
      email: "nina@id8nxt.com",
      mobile: "+1234567894",
      hoverImg:
        "https://img.freepik.com/premium-photo/financier-business-woman-works-computer-accountant-company-s-finances_283470-2057.jpg?semt=ais_hybrid",
      img: "https://img.freepik.com/premium-photo/financier-business-woman-works-computer-accountant-company-s-finances_283470-2057.jpg?semt=ais_hybrid",
    },
  ],
  "Account Team": [
    {
      name: "Aminah Sayed",
      position: "Lead Key Account Manager",
      email: "amina@site.com",
      mobile: "+9876543210",
      img: "https://img.freepik.com/free-photo/brunette-business-woman-with-wavy-long-hair-blue-eyes-stands-holding-notebook-hands_197531-343.jpg?semt=ais_hybrid",
    },
    {
      name: "Sam Patel",
      position: "Account Manager",
      email: "sam@site.com",
      mobile: "+9876543211",
      img: "https://img.freepik.com/free-photo/business-male-with-laptop_23-2148479539.jpg?semt=ais_hybrid",
    },
    {
      name: "Sophia Loren",
      position: "Assistant Manager",
      email: "sophia@site.com",
      mobile: "+9876543212",
      img: "https://img.freepik.com/premium-photo/portrait-indian-businesswoman-white-background-holding-laptop_665346-22333.jpg?semt=ais_hybrid",
    },
    {
      name: "Jake Long",
      position: "Junior Account Manager",
      email: "jake@site.com",
      mobile: "+9876543213",
      img: "https://img.freepik.com/free-photo/portrait-indian-happy-businessman-using-laptop-computer-office_231208-2580.jpg?semt=ais_hybrid",
    },
    {
      name: "Atul Soneeth",
      position: "CEO/Editor",
      email: "atul@site.com",
      mobile: "+1234567890",
      img: "https://img.freepik.com/free-photo/portrait-indian-happy-businessman-using-laptop-computer-office_231208-2580.jpg?semt=ais_hybrid",
    },
    {
      name: "Jane Doe",
      position: "Editor-in-Chief",
      email: "jane@site.com",
      mobile: "+1234567891",
      img: "https://img.freepik.com/free-photo/business-male-with-laptop_23-2148479539.jpg?semt=ais_hybrid",
    },
    {
      name: "Mark Smith",
      position: "Senior Editor",
      email: "mark@site.com",
      mobile: "+1234567892",
      img: "https://img.freepik.com/free-photo/handsome-businessman-work-with-digital-tablet_329181-9117.jpg?semt=ais_hybrid",
    },
    {
      name: "Lisa Wong",
      position: "Assistant Editor",
      email: "lisa@site.com",
      mobile: "+1234567893",
      img: "https://img.freepik.com/premium-photo/business-woman-office-portrait-arms-crossed-lawyer-employee-law-firm-vision-company-worker-female-person-with-confidence-proud-from-professional-attorney-job-work-success_590464-189532.jpg?semt=ais_hybrid",
    },
    {
      name: "Nina Patel",
      position: "Content Strategist",
      email: "nina@site.com",
      mobile: "+1234567894",
      img: "https://img.freepik.com/premium-photo/financier-business-woman-works-computer-accountant-company-s-finances_283470-2057.jpg?semt=ais_hybrid",
    },
  ],
  "Creative Team": [
    {
      name: "Jane Doe",
      position: "Editor-in-Chief",
      email: "jane@site.com",
      mobile: "+1234567891",
      img: "https://img.freepik.com/free-photo/business-male-with-laptop_23-2148479539.jpg?semt=ais_hybrid",
    },
    {
      name: "Mark Smith",
      position: "Senior Editor",
      email: "mark@site.com",
      mobile: "+1234567892",
      img: "https://img.freepik.com/free-photo/handsome-businessman-work-with-digital-tablet_329181-9117.jpg?semt=ais_hybrid",
    },
    {
      name: "Lisa Wong",
      position: "Assistant Editor",
      email: "lisa@site.com",
      mobile: "+1234567893",
      img: "https://img.freepik.com/premium-photo/business-woman-office-portrait-arms-crossed-lawyer-employee-law-firm-vision-company-worker-female-person-with-confidence-proud-from-professional-attorney-job-work-success_590464-189532.jpg?semt=ais_hybrid",
    },
    {
      name: "Asif Akbar",
      position: "Creative Director",
      email: "asif@site.com",
      mobile: "+1928374650",
      img: "https://img.freepik.com/free-photo/cheerful-businessman-working-office_144627-15551.jpg",
    },
    {
      name: "Atul Soneeth",
      position: "CEO/Editor",
      email: "atul@site.com",
      mobile: "+1234567890",
      img: "https://img.freepik.com/free-photo/portrait-indian-happy-businessman-using-laptop-computer-office_231208-2580.jpg?semt=ais_hybrid",
    },
    {
      name: "Nina Patel",
      position: "Content Strategist",
      email: "nina@site.com",
      mobile: "+1234567894",
      img: "https://img.freepik.com/premium-photo/financier-business-woman-works-computer-accountant-company-s-finances_283470-2057.jpg?semt=ais_hybrid",
    },
    {
      name: "Sophia Lee",
      position: "UX Designer",
      email: "sophia.lee@site.com",
      mobile: "+1928374655",
      img: "https://img.freepik.com/free-photo/young-businesswoman-working-office_144627-15554.jpg",
    },
  ],
  "Sales Team": [
    {
      name: "Mark Smith",
      position: "Senior Editor",
      email: "mark@site.com",
      mobile: "+1234567892",
      img: "https://img.freepik.com/free-photo/handsome-businessman-work-with-digital-tablet_329181-9117.jpg?semt=ais_hybrid",
    },
    {
      name: "Atul Soneeth",
      position: "CEO/Editor",
      email: "atul@site.com",
      mobile: "+1234567890",
      img: "https://img.freepik.com/free-photo/portrait-indian-happy-businessman-using-laptop-computer-office_231208-2580.jpg?semt=ais_hybrid",
    },
    {
      name: "Jane Doe",
      position: "Editor-in-Chief",
      email: "jane@site.com",
      mobile: "+1234567891",
      img: "https://img.freepik.com/free-photo/business-male-with-laptop_23-2148479539.jpg?semt=ais_hybrid",
    },

    {
      name: "Nina Patel",
      position: "Content Strategist",
      email: "nina@site.com",
      mobile: "+1234567894",
      img: "https://img.freepik.com/premium-photo/financier-business-woman-works-computer-accountant-company-s-finances_283470-2057.jpg?semt=ais_hybrid",
    },

    {
      name: "Lisa Wong",
      position: "Assistant Editor",
      email: "lisa@site.com",
      mobile: "+1234567893",
      img: "https://img.freepik.com/premium-photo/business-woman-office-portrait-arms-crossed-lawyer-employee-law-firm-vision-company-worker-female-person-with-confidence-proud-from-professional-attorney-job-work-success_590464-189532.jpg?semt=ais_hybrid",
    },
  ],
};
